### ISSUE TITLE
Assembly for Javascript---infinite loop

### ISSUE THREAD

**Issue by narraritwin** [Headline/discord-compiler-bot#132] opened 2022-03-04 19:29 UTC
The following code hasn't finished being compiled into assembly (via `;asm js`), and it's been 45 minutes.

```js
for (let i = 0; i<i+++--i; i+=i--+(++i)) {
  console.log(i);
}
```

**Comment by Headline** [comment] 2022-03-04 20:09
Hi! Thanks for submitting

This is a duplicate of #121, the request never left the bot and errored out before any type of processing could take place. Only languages with the `*` in the `;languages` command can have their assembly viewed.

**Closed by Headline** 2022-03-04 20:09 UTC

**Comment by narraritwin** [comment] 2022-03-06 23:20
Perhaps the bot could reply with some message then? Such as
```
Cannot compile {language} to assembly.
```

**Comment by Headline** [comment] 2022-03-07 19:15
Right, just submitted a patch to cover this. The change should now be reflected on the live bot. Thanks again!
